---
- hosts: opencart, aws_opencart
  become: true
  # vars_files:
  #   - vars/params.yml

  tasks:

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        #search_regex: OpenSSH
        delay: 10
      vars:
        ansible_connection: local

    - name: Wait until Cloud init is done
      wait_for:
        path: /tmp/cloudInitDone.log

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/opencart.{{ avi_gslb.dns_configs.0.domain_name }}.conf"
      notify: Reload Apache

    - name: Enable new site
      shell: "/usr/sbin/a2ensite opencart.{{ avi_gslb.dns_configs.0.domain_name }}.conf"
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Reload Apache

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port | default ('80') }}"
      ufw:
        rule: allow
        port: "{{ http_port | default ('80') }}"
        proto: tcp


    - name: Install Opencart app
      become: true
      shell: |
        php /var/www/"opencart.{{ avi_gslb.dns_configs.0.domain_name }}"/install/cli_install.php install \
        --db_hostname "{{ mysql_db_hostname }}" --db_username "{{ mysql_db_user | default('opencart') }}" \
        --db_password "{{ mysql_db_password | default('opencart') }}" --db_database "{{ mysql_db | default('opencart') }}" \
        --db_driver mysqli --dbport "{{ mysql_db_port | default('3306') }}" --username "{{ opencart_user | default('admin') }}" \
        --password "{{ opencart_password | default('opencart') }}" --email "{{ opencart_email | default('opencart@avidemo.fr') }}" \
        --http_server https://"opencart.{{ avi_gslb.dns_configs.0.domain_name }}"/
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0
      tags:
        - test

    #     php ./cli_install.php install --db_hostname 192.168.142.134 --db_username opencart --db_password opencart --db_database opencart --db_driver mysqli --dbport 3306 --username admin --password opencart --email nicolas.bayle.it@gmail.com --http_server http://192.168.142.133/

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
